id: P001716
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG20781
  title: རབ་རྣོ་སུམ་འཛོམས།
  author: ''
  volumes:
    abc6f865f7024b068b2b52a9fa076661:
      image_group_id: I1KG20829
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
